sub-F1/sub-F1_ses-20190407T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F1/sub-F1_ses-20190409T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F1/sub-F1_ses-20190411T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F1/sub-F1_ses-20190413T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F1/sub-F1_ses-20190414T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F1/sub-F1_ses-20190415T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F1/sub-F1_ses-20190416T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190407T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190409T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190411T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190413T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190414T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190415T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190416T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F2/sub-F2_ses-20190417T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F3/sub-F3_ses-20190407T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F3/sub-F3_ses-20190409T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F3/sub-F3_ses-20190411T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F3/sub-F3_ses-20190413T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F3/sub-F3_ses-20190414T210000_obj-7vehp4_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F3/sub-F3_ses-20190414T210000_obj-n4e7d4_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190407T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190409T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190411T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190413T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190414T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190415T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190416T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190417T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-F5/sub-F5_ses-20190418T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190901T210000_ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190824T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190827T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190829T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190901T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190902T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190903T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190904T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R4/sub-R4_ses-20190905T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190209T210000_obj-bxnk6r_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190209T210000_obj-ecljfx_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190211T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190214T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190216T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190218T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190220T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190221T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190222T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R1/sub-R1_ses-20190223T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190206T210000_obj-16d9pmi_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190206T210000_obj-1m6ibdg_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190206T210000_ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190209T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190211T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190214T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190216T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190217T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190218T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190219T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190220T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R2/sub-R2_ses-20190221T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190209T210000_obj-1m489i9_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190209T210000_obj-1uiqbl9_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190211T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190214T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190216T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190218T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190220T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190221T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190222T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R3/sub-R3_ses-20190223T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R5/sub-R5_ses-20200313T210000_ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R5/sub-R5_ses-20200317T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R5/sub-R5_ses-20200319T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R5/sub-R5_ses-20200320T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R5/sub-R5_ses-20200321T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200206T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200207T210000_ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200208T210000_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200209T210000_obj-1ouyda4_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200209T210000_obj-1plurd8_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200210T210000_obj-10qdhbr_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200210T210000_obj-1t1rfdq_behavior+ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200210T210000_obj-qb15q4_ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-R6/sub-R6_ses-20200210T210000_obj-r0awni_ophys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

